### PR TITLE
Add `.pre-commit-config.yaml`

### PR DESCRIPTION
**Pull request by jwodder**

### CODE REVIEW

**Comment by yarikoptic** [comment]
should we have a ci to run it ?

**Comment by jwodder** [comment]
@yarikoptic The CI already runs linting, and we don't run pre-commit in CI anywhere else.

**Comment by yarikoptic** [comment]
> @yarikoptic The CI already runs linting, and we don't run pre-commit in CI anywhere else.

but I think we should 

<details>
<summary>(and I saw a number of projects which do)</summary> 

```shell
❯ grep -l pre-commit.*run */.github/workflows/*
aiohttp_retry/.github/workflows/python-package.yml
briefcase/.github/workflows/ci.yml
home-assistant/.github/workflows/ci.yaml
lazy_loader/.github/workflows/lint.yml
mamba/.github/workflows/linters.yml
networkx/.github/workflows/lint.yml
prefect/.github/workflows/static-analysis.yaml
```
</details>

so that there is no unexpected changes/complains then from pre-commit for PRs which managed to be submitted by someone who did not use pre-commit.

**Comment by jwodder** [comment]
@AlmightyYakob Ping.

**Comment by AlmightyYakob** [comment]
If we have anything we'd like to enforce before things are merged, that should be done in CI, since nobody is forced to use pre-commit, and I certainly have no intention of doing so either.

That being said, `black`, `isort` and `flake8` are being run in CI, so the only difference between these hooks and CI is the first entry in that list, the `pre-commit-hooks` repo. If it aids developer workflow, I'm okay with it.

**Review by AlmightyYakob — APPROVED** [review]

**Pull request merged**
